services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Websedit\WeCookieConsent\:
        resource: '../Classes/*'
        exclude: '../Classes/Domain/Model/*'
